name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  publish:
    needs: tests
    if: github.event_name == 'release'
    uses: ./.github/workflows/publish.yml
    permissions:
      id-token: write
