name: Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - name: Install dependencies
        run: pdm install --no-lock --dev
      - name: Run Ruff linter
        run: pdm run ruff check . --no-fix
      - name: Run Ruff formatter
        run: pdm run ruff format . --check
      - name: Run Pyright
        run: pdm run basedpyright
